name: Test Carthage AWS Plugin
on:
  push: {}
  schedule:
    - cron: '42 23 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt -q update
          sudo apt -y install systemd-container socat qemu-utils fai-setup-storage fai-server python3-mako python3-sh python3-pyvmomi python3-yaml python3-pytest ansible genisoimage python3-boto3 

      - name: run tests
        run: |
          git clone https://github.com/hadron/carthage
                     PYTHONPATH=.:carthage pytest-3 -v --carthage-config=.github/test_config.yml --log-cli-level=debug tests
          