name: Test Carthage AWS Plugin
concurrency: there_can_only_be_one
on:
  push: {}
  schedule:
    - cron: '42 23 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          podman pull ghcr..io/hadron/carthage:latest
          podman run -v`pwd`:/carthage_aws -d --name carthage --privileged --device=/dev/fuse run carthage:latest
          podman exec carthage apt update
          podman exec carthage apt -y install python3-pytest python3-boto3

      - name: run tests
        run: |
          podman exec -ti -w/carthage_aws carthage pytest-3 -v --carthage-config=.github/test_config.yml